### ISSUE TITLE
Use Stream API for faster responses

### ISSUE THREAD

**Issue by semihsezer** [sebhs/human-reader-chrome-extension#17]
As mentioned on a feedback on Chrome Store review, using the stream library will be helpful for faster response times.

**Comment by semihsezer** [comment]
@sebhs sorry my bad! I directly went from the comment on Chrome Store. Feel free to respond to Daniel Roșu-Gutman's review there if you want to tell him it is implemented :)

**Comment by sebhs** [comment]
Good point! @semihsezer
