### ISSUE TITLE
Repeatedly getting "Unauthorized: please set your api key"

### ISSUE THREAD

**Issue by jcharle4** [sebhs/human-reader-chrome-extension#25]
Is there a way to correct this "Unauthorized: please set your API key" even after entering the API key? The extension accepts the API key in the settings. But then, when selecting text to read, the error message pops up again.

**Comment by sebhs** [comment]
@jcharle4 any chance you have any steps to reproduce this? Are you sure your API key is valid? I haven't seen this pop up before. 

Maybe you can check the network tab, I might be missing something in the error handling

**Comment by jcharle4** [comment]
Sorry, it was user error. Afterwards, I realized that the quota for my API key was running low. So, whenever I selected a block of text that exceeded the remaining quota, the extension would drop the API key and prompt me to re-enter an API key. However, if I selected just a few characters, it would work as expected. 

Thank you so much for your awesome work on this project!!
